'use strict';
const $=selector=>document.querySelector(selector);
const labels={wire:'Wireframe',geo:'Geometric',dot:'Dots',symbol:'Symbols',outline:'Outlines'};
const noTilt=new Set(['bloom','tunnel','rings','vortex','grid','fan','stripedSphere','petalSphere','venn','venn3','fibonacci','sine','hyperbola','cube','pyramid','spider','squares','nested','squareflower','bowtie','arcs','rosette','ripple','halftone','bars','lissajous','hypotrochoid','epitrochoid','rose','superellipse','polygonspiral','cardioid','sunflower','dotspiral','dotripple','dotdiamond','doublespiral','astroid','nephroid','lemniscate','chrysanthemum','starweave','hexnest','trianglefan','wavecircle','offsetellipses','braid','conchoid','cycloid','dotflower']);
for(const [id,,cat] of variationForms)if(cat!=='wire'&&id!=='cylinderNodes')noTilt.add(id);
const noTwist=new Set(['fan','axes','cube','pyramid','bowtie','squareGrid']);
const twistLabels={venn:'Separation',venn3:'Separation',rings:'Offset',spider:'Spokes',halftone:'Dot gradient',dotRing:'Ring count',lens:'Separation',rosette:'Petals',ripple:'Waves',sine:'Frequency',bars:'Gap',lissajous:'Frequency',rose:'Petals',polygonspiral:'Sides',cardioid:'Multiplier',superellipse:'Curvature',sunflower:'Divergence',dotspiral:'Turns',dotripple:'Phase',dotdiamond:'Dot size',shell:'Turns',helicoid:'Turns',saddle:'Curvature',twistedprism:'Sides',doublespiral:'Turns',astroid:'Curvature',chrysanthemum:'Petals',starweave:'Points',dotflower:'Petals',braid:'Frequency',cycloid:'Amplitude',trefoil:'Weave',torusknot:'Weave',paraboloid:'Meridian twist',droplet:'Meridian twist'};
const spatialForms=new Set(['enneperSurface','torusLink','rippleVase','spiralShell3','twistedSail','figureKnot','torus','sphere','dots','mobius','trefoil','torusknot','saddle','helicoid','shell','ribbon','ellipsoid','ripplefield','dottorus','catenoid','paraboloid','onion','droplet','dome','twistedprism','rippledisc','dotcone','dotcylinder','dotvase','warpedTorus','saddleTorus','pinchedTorus','flutedSphere','meltedSphere','spikedSphere','dentedCube','meltedCube','crownCube','waveCube','ribbonLoop','orbitalCage','duneField','twistedHalo','molecularShell','spatialCircuit','fragmentedOrbit','beadedTwist']);
const ranges={axisX:[-180,180,1],axisY:[-180,180,1],axisZ:[-180,180,1],density:[6,60,1],twist:[0,100,1],tilt:[5,85,1],rotation:[-180,180,1],scale:[30,120,1],stroke:[.4,4,.1]};
function shapeDefaults(type){const category=forms.find(f=>f[0]===type)[2];return {...defaults,type,variant:0,density:category==='outline'?6:category==='symbol'?18:category==='geo'?18:24,rotation:category==='wire'?-25:0,twist:35,...({venn:{density:22,twist:40},venn3:{density:22,twist:30},lens:{density:12,twist:25},petalSphere:{density:18},bloom:{density:8},rosette:{density:18},ripple:{density:18},fibonacci:{density:18},sunflower:{density:40,twist:0},starPrism:{density:33,twist:35,stroke:1.7},vectorBurst:{density:33,twist:35,stroke:1.7},signalRing:{density:29,twist:35,stroke:1.7},rippleCorona:{density:22,twist:35,stroke:.8},fragmentedOrbit:{density:24,tilt:72,rotation:-18,stroke:1},beadedTwist:{density:24,tilt:45,rotation:-35,stroke:.8},torus:{density:28},sphere:{density:20},mobius:{density:22},trefoil:{density:18,stroke:.8},torusknot:{density:18,stroke:.8},braid:{density:18,twist:20,stroke:.8},ribbon:{density:14,stroke:1},conchoid:{density:12,stroke:.8},offsetellipses:{density:12,stroke:.8},dome:{density:15,stroke:.8},doublespiral:{density:12,stroke:1}}[type]||{})}}
state=shapeDefaults('torus');
let pendingFrame=0,toastTimer;
const past=[],future=[],shapeEdits=new Map();
function snapshot(){return {...state}}
function same(a,b){return JSON.stringify(a)===JSON.stringify(b)}
function remember(previous){if(same(previous,state))return;past.push(previous);if(past.length>80)past.shift();future.length=0;syncHistory()}
function change(next){const old=snapshot();Object.assign(state,next);remember(old);render()}
function syncHistory(){}
function undo(){if(!past.length)return;future.push(snapshot());state=past.pop();render()}
function redo(){if(!future.length)return;past.push(snapshot());state=future.pop();render()}
function select(type){if(type===state.type)return;shapeEdits.set(state.type,snapshot());change(shapeEdits.get(type)||shapeDefaults(type));const selected=$(`[data-type="${type}"]`);selected?.scrollIntoView({block:'nearest',inline:'nearest'})}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2400)}
function scheduleArt(){if(!pendingFrame)pendingFrame=requestAnimationFrame(()=>{pendingFrame=0;draw()})}
function draw(){$('#art').innerHTML=content(state).markup}
function syncControls(){const variants=shapeFamilies[state.type];$('#variation-control').hidden=!variants;$('#variation').innerHTML=(variants||[]).map(([id,label],i)=>`<option value="${i}">${label}</option>`).join('');$('#variation').value=state.variant||0;const dot=forms.find(f=>f[0]===state.type)[2]==='dot';for(const [key] of Object.entries(ranges)){const range=$('#'+key),number=$('#'+key+'-number');range.value=state[key];number.value=state[key];range.style.setProperty('--fill',((state[key]-ranges[key][0])/(ranges[key][1]-ranges[key][0])*100)+'%');const hidden=key.startsWith('axis')&&!spatialForms.has(state.type)||key==='tilt'&&noTilt.has(state.type)||key==='twist'&&noTwist.has(state.type);range.closest('.control').hidden=hidden}$('#twist-label').textContent=(shapeFamilies[state.type]?'Deformation':twistLabels[state.type])||'Twist';$('#stroke-label').textContent=dot?'Dot size':'Stroke width';$('#stroke-unit').textContent=dot?'':'px';$('#stroke-number').setAttribute('aria-label',dot?'Dot size value':'Stroke width value');$('#density-label').textContent=forms.find(f=>f[0]===state.type)[2]==='outline'?'Detail':'Density'}
function render(){$('#art').classList.toggle('rotatable',spatialForms.has(state.type));$('#drag-hint').hidden=!spatialForms.has(state.type);syncControls();draw();const form=forms.find(f=>f[0]===state.type);$('#shape-title').textContent=form[1];$('#shape-category').textContent=labels[form[2]];$('#art').setAttribute('aria-label',form[1]+' vector preview');document.querySelectorAll('.preset').forEach(button=>{const active=button.dataset.type===state.type;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});syncHistory()}
function makeControls(){const variantControl=document.createElement('div');variantControl.className='control';variantControl.id='variation-control';variantControl.innerHTML='<div class="control-top"><label for="variation">Variation</label></div><select id="variation" aria-label="Shape variation"></select>';$('#sliders').append(variantControl);$('#variation').onchange=e=>change({variant:Number(e.target.value)});for(const [key,[min,max,step]] of Object.entries(ranges)){const name={axisX:'X axis',axisY:'Y axis',axisZ:'Z axis',density:'Density',twist:'Twist',tilt:'Tilt',rotation:'Rotation',scale:'Scale',stroke:'Stroke width'}[key],unit={axisX:'°',axisY:'°',axisZ:'°',rotation:'°',tilt:'°',scale:'%',stroke:'px'}[key]||'';const el=document.createElement('div');el.className='control';el.innerHTML=`<div class="control-top"><label id="${key}-label" for="${key}">${name}</label><div class="number-wrap"><input type="number" id="${key}-number" aria-label="${name} value" min="${min}" max="${max}" step="${step}" inputmode="decimal"><span id="${key}-unit">${unit}</span></div></div><input type="range" id="${key}" min="${min}" max="${max}" step="${step}" aria-labelledby="${key}-label">`;$(key==='stroke'?'#appearance-controls':'#sliders').append(el);let before;const range=$('#'+key);range.addEventListener('pointerdown',()=>{before=snapshot()});range.addEventListener('keydown',()=>{if(!before)before=snapshot()});range.addEventListener('input',()=>{if(!before)before=snapshot();state[key]=Number(range.value);syncControls();scheduleArt()});const commit=()=>{if(before){remember(before);before=null}};range.addEventListener('change',commit);range.addEventListener('blur',commit);const number=$('#'+key+'-number');number.addEventListener('change',()=>{const raw=number.valueAsNumber;if(!Number.isFinite(raw)){syncControls();return}const value=Number((Math.round(Math.max(min,Math.min(max,raw))/step)*step).toFixed(1));change({[key]:value})});number.addEventListener('keydown',e=>{if(e.key==='Enter')number.blur()})}}
function makeLibrary(){const fragment=document.createDocumentFragment();for(const [id,name,cat] of forms){const button=document.createElement('button');button.className='preset';button.dataset.type=id;button.dataset.category=cat;button.dataset.name=name.toLowerCase();button.setAttribute('aria-label',name+' shape');button.setAttribute('aria-pressed',String(id===state.type));button.innerHTML=`<small class="preset-index">${String(forms.findIndex(f=>f[0]===id)+1).padStart(3,'0')}</small><svg viewBox="0 0 600 600" aria-hidden="true"></svg><span>${name}</span>`;button.onclick=()=>select(id);fragment.append(button)}$('#presets').append(fragment);const renderThumb=button=>{if(button.dataset.ready)return;const s={...shapeDefaults(button.dataset.type),scale:92,stroke:2};s.density=Math.min(s.density,forms.find(f=>f[0]===s.type)[2]==='dot'?20:16);button.querySelector('svg').innerHTML=content(s).markup;button.dataset.ready='true'};if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){renderThumb(e.target);observer.unobserve(e.target)}},{rootMargin:'200px'});document.querySelectorAll('.preset').forEach(b=>observer.observe(b))}else document.querySelectorAll('.preset').forEach(renderThumb)}
function xmlText(value){return value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function exportSVG(){const size=Number($('#size').value),name=forms.find(f=>f[0]===state.type)[1],transparent=$('#transparent').checked;return `<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 600 600"><title>${xmlText(name)} — geoshapez</title><desc>Editable vector artwork. Black paths on ${transparent?'a transparent':'a white'} background.</desc>${transparent?'':'<rect id="background" width="600" height="600" fill="#ffffff"/>'}${content(state).markup}</svg>`}
function download(){const blob=new Blob([exportSVG()],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`geoshapez-${state.type}-${$('#size').value}.svg`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('SVG exported')}
function randomize(){const next={density:12+Math.floor(Math.random()*29),rotation:Math.floor(Math.random()*25)*15-180};if(!noTwist.has(state.type))next.twist=Math.floor(Math.random()*101);if(!noTilt.has(state.type))next.tilt=25+Math.floor(Math.random()*46);change(next)}
$('#form-count').textContent=forms.length;
makeControls();makeLibrary();render();
$('#download').onclick=download;$('#reset').onclick=()=>{change(shapeDefaults(state.type));toast('Shape reset')};$('#random').onclick=randomize;$('#grid').onclick=()=>{const hidden=$('#canvas-wrap').classList.toggle('no-grid');$('#grid').setAttribute('aria-pressed',String(!hidden))};$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(exportSVG());toast('SVG copied to clipboard')}catch{const dialog=$('#copy-dialog');$('#svg-source').value=exportSVG();dialog.showModal();$('#svg-source').focus();$('#svg-source').select()}};$('#close-copy').onclick=()=>$('#copy-dialog').close();
document.addEventListener('keydown',e=>{const editing=e.target.matches('input,textarea,select');if(!editing&&(e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}});
const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_shape',description:'Select a geoshapez shape and adjust its geometry. Changes appear in the editor and can be undone.',inputSchema:{type:'object',properties:{type:{type:'string',enum:forms.map(f=>f[0])},...Object.fromEntries(Object.entries(ranges).map(([key,[min,max,step]])=>[key,{type:step===1?'integer':'number',minimum:min,maximum:max}]))},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Expected a shape configuration');for(const [key,value] of Object.entries(input)){if(key==='type'){if(!forms.some(f=>f[0]===value))throw Error('Unknown shape')}else{const range=ranges[key];if(!range||typeof value!=='number'||!Number.isFinite(value)||value<range[0]||value>range[1]||range[2]===1&&!Number.isInteger(value))throw Error('Invalid '+key)}}const next=input.type&&input.type!==state.type?{...shapeDefaults(input.type),...input}:input;change(next);return {type:state.type,density:state.density,twist:state.twist,tilt:state.tilt,rotation:state.rotation,scale:state.scale,stroke:state.stroke}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}


let dragState=null;
const wrapAngle=v=>((Math.round(v)+180)%360+360)%360-180;
$('#art').addEventListener('pointerdown',e=>{if(!spatialForms.has(state.type)||e.button!==0)return;e.preventDefault();dragState={x:e.clientX,y:e.clientY,before:snapshot()};$('#art').setPointerCapture(e.pointerId);$('#art').classList.add('dragging')});
$('#art').addEventListener('pointermove',e=>{if(!dragState)return;state.axisY=wrapAngle(dragState.before.axisY+(e.clientX-dragState.x)*.65);state.axisX=wrapAngle(dragState.before.axisX-(e.clientY-dragState.y)*.65);syncControls();scheduleArt()});
function finishRotation(){if(!dragState)return;remember(dragState.before);dragState=null;$('#art').classList.remove('dragging')}
$('#art').addEventListener('pointerup',finishRotation);$('#art').addEventListener('pointercancel',finishRotation);$('#art').addEventListener('lostpointercapture',finishRotation);
