const extraForms=[
['cone','Cone','wire'],['cylinder','Cylinder','wire'],['doublecone','Double cone','wire'],['mobius','Möbius strip','wire'],['spring','Spring','wire'],['fan','String art','wire'],['stripedSphere','Striped sphere','wire'],['petalSphere','Petal sphere','geo'],
['venn','Venn diagram','geo'],['venn3','Triple Venn','geo'],['fibonacci','Golden spiral','geo'],['axes','Isometric grid','geo'],['sine','Sine wave','geo'],['hyperbola','Hyperbola','geo'],['cube','Cube lattice','wire'],['pyramid','Pyramid','geo'],['spider','Radial web','wire'],['squares','Square chain','geo'],['nested','Nested squares','geo'],['squareflower','Square bloom','geo'],['bowtie','Bow tie','geo'],['arcs','Arc connections','geo'],['rosette','Spirograph','wire'],['ripple','Wavy rings','geo'],['halftone','Halftone','dot'],['dotRing','Dotted rings','dot'],['bars','Split bars','geo'],['lens','Double ellipse','geo'],
['trefoil','Trefoil knot','wire'],['torusknot','Torus knot','wire'],['saddle','Saddle surface','wire'],['helicoid','Helicoid','wire'],['shell','Spiral shell','wire'],['ribbon','Wave ribbon','wire'],['ellipsoid','Ellipsoid','wire'],['ripplefield','Ripple field','wire'],['lissajous','Lissajous','geo'],['hypotrochoid','Hypotrochoid','geo'],['epitrochoid','Epitrochoid','geo'],['rose','Polar rose','geo'],['superellipse','Superellipse','geo'],['polygonspiral','Polygon spiral','geo'],['cardioid','Cardioid weave','geo'],['sunflower','Sunflower','dot'],['dotspiral','Dot spiral','dot'],['dottorus','Dot torus','dot'],['dotripple','Dot ripples','dot'],['dotdiamond','Dot diamond','dot'],
['catenoid', 'Catenoid', 'wire'],['paraboloid', 'Paraboloid', 'wire'],['dome', 'Triangulated dome', 'wire'],['twistedprism', 'Twisted prism', 'wire'],['doublespiral', 'Double spiral', 'geo'],['astroid', 'Astroid', 'geo'],['nephroid', 'Nephroid', 'geo'],['lemniscate', 'Infinity curves', 'geo'],['chrysanthemum', 'Chrysanthemum', 'geo'],['starweave', 'Star weave', 'geo'],['hexnest', 'Hexagon nest', 'geo'],['trianglefan', 'Triangle fan', 'geo'],['wavecircle', 'Wave circle', 'geo'],['offsetellipses', 'Offset ellipses', 'geo'],['rippledisc', 'Ripple disc', 'wire'],['braid', 'Braided waves', 'wire'],['droplet', 'Droplet', 'wire'],['onion', 'Onion surface', 'wire'],['conchoid', 'Conchoid', 'geo'],['cycloid', 'Cycloid', 'geo'],['dotcone', 'Dot cone', 'dot'],['dotcylinder', 'Dot cylinder', 'dot'],['dotvase', 'Dot vase', 'dot'],['dotflower', 'Dot flower', 'dot']
];
function appendGeometry(s,h){const {out,n,tw,tilt,f,path,curve,circle,project}=h;const line=(a,b)=>path([a,b]);const dot=(x,y,r)=>out.push(`<circle cx="${f(x)}" cy="${f(y)}" r="${f(r)}" fill="currentColor" stroke="none"/>`);const ellipse=(x,y,rx,ry)=>curve(t=>[x+rx*Math.cos(t),y+ry*Math.sin(t)]);const arrow=(a,b)=>{line(a,b);let t=Math.atan2(b[1]-a[1],b[0]-a[0]);for(const k of [-.5,.5])line(b,[b[0]-10*Math.cos(t+k),b[1]-10*Math.sin(t+k)])};const iso=(x,y,z)=>[(x-y)*.78,(x+y)*.35-z];
if(s.type==='cone'||s.type==='doublecone'){let both=s.type==='doublecone',ry=18+50*Math.sin(tilt),height=both?150:140;for(let j=0;j<n;j++){let a=j/n*TAU;line([0,both?0:-170],[145*Math.cos(a),height+ry*Math.sin(a)]);if(both)line([0,0],[145*Math.cos(a),-height+ry*Math.sin(a)])}let rings=Math.max(3,Math.round(3+tw*16));for(let j=1;j<=rings;j++){let k=j/rings;ellipse(0,both?height*k:-170+310*k,145*k,ry*k);if(both)ellipse(0,-height*k,145*k,ry*k)}}
if(s.type==='cylinder'){let ry=15+60*Math.sin(tilt);for(let j=0;j<n;j++){let a=j/n*TAU,b=a+tw;line([140*Math.cos(a),-120+ry*Math.sin(a)],[140*Math.cos(b),120+ry*Math.sin(b)])}ellipse(0,-120,140,ry);ellipse(0,120,140,ry);for(let j=1;j<=Math.round(tw*8);j++)ellipse(0,-120+j/(Math.round(tw*8)+1)*240,140,ry)}
if(s.type==='mobius'){for(let j=0;j<n;j++){let w=(j/(n-1)-.5)*105;curve(t=>{let r=135+w*Math.cos(t*(.5+Math.round(tw*2)));return project(r*Math.cos(t),r*Math.sin(t),w*Math.sin(t*(.5+Math.round(tw*2))))},220)}for(let j=0;j<n;j++){let t=j/n*TAU;path(Array.from({length:25},(_,i)=>{let w=(i/24-.5)*105,r=135+w*Math.cos(t*(.5+Math.round(tw*2)));return project(r*Math.cos(t),r*Math.sin(t),w*Math.sin(t*(.5+Math.round(tw*2))))}))}}
if(s.type==='spring'){let turns=3+n/5;path(Array.from({length:Math.ceil(turns*100)},(_,i)=>{let u=i/(Math.ceil(turns*100)-1),t=u*TAU*turns;return [(115+tw*30*Math.cos(u*TAU))*Math.cos(t),(u-.5)*300+35*Math.sin(t)*Math.sin(tilt)]}))}
if(s.type==='fan'){for(let j=0;j<n;j++){let u=j/(n-1);line([-180+360*u,170],[-180,-170+340*u]);line([180-360*u,-170],[180,170-340*u])}}
if(s.type==='stripedSphere'){for(let j=1;j<n;j++){let y=(j/n-.5)*360,r=Math.sqrt(180*180-y*y);path(Array.from({length:101},(_,i)=>{let x=(i/100-.5)*2*r;return [x,y+tw*35*Math.sin(x/180*Math.PI)*Math.sqrt(1-y*y/32400)]}))}circle(0,0,180)}
if(s.type==='petalSphere'){let k=Math.max(3,Math.round(n/3));for(let j=0;j<k;j++){let a=j/k*Math.PI;curve(t=>[180*Math.sin(t)*Math.cos(a),180*Math.cos(t)]);if(tw>.4)curve(t=>[180*Math.cos(t),70*Math.sin(t)*Math.sin(a)])}}
if(s.type==='venn'||s.type==='venn3'){let three=s.type==='venn3',r=115,d=35+tw*70;let cs=three?[[0,-d],[-d*.866,d/2],[d*.866,d/2]]:[[-d,0],[d,0]];cs.forEach(p=>circle(...p,r));for(let j=0;j<n;j++){let c=-220+j/(n-1)*440,pts=[];for(let i=0;i<=400;i++){let x=-200+i,y=x*.65+c;if(cs.every(p=>(x-p[0])**2+(y-p[1])**2<=r*r))pts.push([x,y])}if(pts.length>1)line(pts[0],pts[pts.length-1])}}
if(s.type==='fibonacci'){let turns=1.5+tw*1.8,k=Math.log(1.618)/(Math.PI/2),start=-turns*TAU;path(Array.from({length:501},(_,i)=>{let a=start+i/500*turns*TAU,r=180*Math.exp(k*a);return [r*Math.cos(a),r*Math.sin(a)]}));for(let j=0;j<Math.min(12,Math.round(n/3));j++){let r=180/Math.pow(1.618,j);path([[-r,-r],[r,-r],[r,r],[-r,r],[-r,-r]])}}
if(s.type==='axes'){let z=60+tilt*70;for(let j=0;j<=n;j++){let k=-110+j/n*220;line(iso(k,-110,0),iso(k,110,0));line(iso(-110,k,0),iso(110,k,0))}arrow(iso(-130,0,0),iso(160,0,0));arrow(iso(0,-130,0),iso(0,160,0));arrow([0,0],[0,-z])}
if(s.type==='sine'){arrow([-200,0],[200,0]);arrow([-110,140],[-110,-150]);let freq=1+tw*2;path(Array.from({length:301},(_,i)=>{let x=-190+i/300*380;return [x,-85*Math.sin((x+110)/380*TAU*freq)]}));for(let j=0;j<n;j++){let x=-110+j/n*380/(freq*2);line([x,0],[x,-85*Math.sin((x+110)/380*TAU*freq)])}}
if(s.type==='hyperbola'){arrow([-195,0],[195,0]);arrow([0,195],[0,-195]);let k=1400+tw*2800;for(let sign of [-1,1])path(Array.from({length:200},(_,i)=>{let x=k/185+i/199*(185-k/185);return [sign*x,-sign*k/x]}));for(let j=0;j<=n;j++){let x=-180+360*j/n;line([x,-3],[x,3]);line([-3,x],[3,x])}}
if(s.type==='cube'){let r=110;for(let j=0;j<=n;j++){let k=-r+j/n*2*r;line(iso(k,-r,-r),iso(k,r,-r));line(iso(-r,k,-r),iso(r,k,-r));line(iso(-r,-r,k),iso(r,-r,k));line(iso(-r,-r,k),iso(-r,r,k))}for(const x of [-r,r])for(const y of [-r,r])line(iso(x,y,-r),iso(x,y,r));path([iso(-r,-r,r),iso(r,-r,r),iso(r,r,r),iso(-r,r,r),iso(-r,-r,r)])}
if(s.type==='pyramid'){let top=[0,-180];for(let j=0;j<n;j++){let k=(j+1)/n,y=-180+340*k,w=175*k;path([top,[-w,y],[w,y],top]);line([0,y-50*k],[-w,y]);line([0,y-50*k],[w,y]);line(top,[0,y-50*k])}}
if(s.type==='spider'){for(let j=1;j<=n;j++)circle(0,0,180*j/n);let count=Math.max(6,Math.round(8+tw*22));for(let j=0;j<count;j++){let a=j/count*TAU;line([0,0],[180*Math.cos(a),180*Math.sin(a)])}}
if(s.type==='squares'){let count=Math.max(3,Math.round(n/4)),w=90+tw*65;for(let j=0;j<count;j++){let d=(j/(count-1)-.5)*(340-w);path([[d-w/2,-d-w/2],[d+w/2,-d-w/2],[d+w/2,-d+w/2],[d-w/2,-d+w/2],[d-w/2,-d-w/2]])}}
if(s.type==='nested'){let count=Math.max(3,Math.round(n/3));circle(0,0,185);for(let j=0;j<count;j++){let r=185*Math.pow(.73,j),a=j*Math.PI/4+tw*.3;path(Array.from({length:5},(_,i)=>[r*Math.cos(i/4*TAU+a),r*Math.sin(i/4*TAU+a)]))}}
if(s.type==='squareflower'){let r=70+tw*45;for(const x of [-95,95])for(const y of [-95,95]){path([[x-r/2,y-r/2],[x+r/2,y-r/2],[x+r/2,y+r/2],[x-r/2,y+r/2],[x-r/2,y-r/2]]);circle(x*.4,y*.4,60)}circle(0,0,45);for(let j=0;j<Math.round(n/10);j++)circle(0,0,15+j*10)}
if(s.type==='bowtie'){for(let j=0;j<n;j++){let x=-180+j/(n-1)*360;line([x,-170],[-x,170])}}
if(s.type==='arcs'){let count=Math.max(4,Math.round(n/3));for(let j=0;j<count;j++){let x=-180+j/(count-1)*360;circle(x,0,9);if(j<count-1){let end=180-j/(count-1)*180,r=(end-x)/2;if(r>0)path(Array.from({length:100},(_,i)=>{let t=i/99*Math.PI;return [x+r-r*Math.cos(t),(j%2?1:-1)*r*Math.sin(t)*( .5+tw)]}))}}}
if(s.type==='rosette'){let lobes=3+Math.round(tw*9);for(let j=0;j<Math.max(1,Math.round(n/6));j++)curve(t=>{let r=125+55*Math.cos(lobes*t+j*.2);return [r*Math.cos(t),r*Math.sin(t)]},480)}
if(s.type==='ripple'){let count=Math.max(2,Math.round(n/6)),lobes=3+Math.round(tw*5);for(let j=0;j<count;j++)curve(t=>{let r=160+23*Math.cos(lobes*t+j/count*TAU);return [r*Math.cos(t),r*Math.sin(t)]},240)}
if(s.type==='halftone'){for(let j=0;j<n;j++)for(let i=0;i<n;i++){let spacing=350/(n-1),r=Math.max(.45,spacing*.38*Math.pow((j+1)/n,.4+tw*2));dot(-175+i*spacing,-175+j*spacing,r)}}
if(s.type==='dotRing'){let rings=Math.max(1,Math.round(1+tw*5));for(let j=0;j<rings;j++)for(let i=0;i<n;i++){let a=i/n*TAU,r=180-j*22;dot(r*Math.cos(a),r*Math.sin(a)*Math.sin(tilt),2.5+(1+Math.sin(a))*2.5)}}
if(s.type==='bars'){let count=Math.max(5,Math.round(n/2));for(let i=0;i<count;i++){let x=(i/(count-1)-.5)*330,y=Math.sqrt(Math.max(0,180*180-x*x))*.6,gap=10+tw*30;line([x,-y],[x,-gap]);line([x,gap],[x,y])}}
if(s.type==='lens'){let gap=8+tw*65;ellipse(0,-gap,180,40+60*Math.sin(tilt));ellipse(0,gap,180,40+60*Math.sin(tilt));for(let j=1;j<Math.round(n/10);j++)ellipse(0,0,180-j*20,40+60*Math.sin(tilt))}

if(s.type==='trefoil'||s.type==='torusknot'){let p=2,q=s.type==='trefoil'?3:5,strands=4+Math.round((n-6)/54*10);for(let j=0;j<strands;j++){let b=j/strands*TAU;curve(t=>{let r=115+44*Math.cos(q*t)+12*Math.cos(b);return project(r*Math.cos(p*t),r*Math.sin(p*t),44*Math.sin(q*t)+12*Math.sin(b+tw*Math.sin(t)))},420)}}
if(s.type==='saddle'){for(let j=0;j<n;j++){let a=(j/(n-1)-.5)*280;for(let swap of [false,true])path(Array.from({length:90},(_,i)=>{let b=(i/89-.5)*280,x=swap?a:b,y=swap?b:a;return project(x,y,(x*x-y*y)/180*(.3+tw))}))}}
if(s.type==='helicoid'){let turns=1+tw*2;for(let j=0;j<n;j++){let r=20+j/(n-1)*125;path(Array.from({length:250},(_,i)=>{let t=i/249*TAU*turns;return project(r*Math.cos(t),r*Math.sin(t),(i/249-.5)*270)}))}for(let j=0;j<n;j++){let t=j/(n-1)*TAU*turns,z=(j/(n-1)-.5)*270;line(project(20*Math.cos(t),20*Math.sin(t),z),project(145*Math.cos(t),145*Math.sin(t),z))}}
if(s.type==='shell'){for(let j=0;j<n;j++){let u=j/(n-1),a=u*TAU*(1.5+tw),r=15+u*95;curve(t=>project((r+u*45*Math.cos(t))*Math.cos(a),(r+u*45*Math.cos(t))*Math.sin(a),(u-.5)*160+u*45*Math.sin(t)),100)}}
if(s.type==='ribbon'){for(let j=0;j<n;j++){let v=(j/(n-1)-.5)*110;path(Array.from({length:180},(_,i)=>{let t=i/179*TAU;return project((i/179-.5)*340,v*Math.cos(t*(1+tw)),65*Math.sin(t)+v*Math.sin(t*(1+tw)))}))}}
if(s.type==='ellipsoid'){for(let j=0;j<n;j++){let a=j/n*Math.PI;curve(t=>project(185*Math.sin(t)*Math.cos(a),100*Math.sin(t)*Math.sin(a),135*Math.cos(t)*( .6+tw*.5)))}}
if(s.type==='ripplefield'){for(let j=0;j<n;j++){let y=(j/(n-1)-.5)*320;path(Array.from({length:160},(_,i)=>{let x=(i/159-.5)*320,r=Math.hypot(x,y);return project(x,y,40*Math.cos(r/28-tw*TAU)*Math.exp(-r/300))}))}}
if(s.type==='lissajous'){let a=2+Math.round(tw*4);for(let j=0;j<Math.max(1,Math.round(n/6));j++)curve(t=>[175*Math.sin(a*t+j*.09),175*Math.sin((a+1)*t)],480)}
if(s.type==='hypotrochoid'||s.type==='epitrochoid'){let k=3+Math.round(tw*6),inside=s.type==='hypotrochoid',a=inside?k-1:k+1;for(let j=0;j<Math.max(1,Math.round(n/6));j++){let d=.4+j*.08,scale=180/(a+d);curve(t=>[scale*(a*Math.cos(t)+(inside?1:-1)*d*Math.cos(a*t)),scale*(a*Math.sin(t)-d*Math.sin(a*t))],600)}}
if(s.type==='rose'){let k=2+Math.round(tw*7);for(let j=0;j<Math.max(1,Math.round(n/5));j++)curve(t=>{let r=(180-j*9)*Math.cos(k*t);return [r*Math.cos(t),r*Math.sin(t)]},480)}
if(s.type==='superellipse'){let power=.4+tw*3;for(let j=0;j<n;j++){let r=180*(j+1)/n;curve(t=>[r*Math.sign(Math.cos(t))*Math.pow(Math.abs(Math.cos(t)),power),r*Math.sign(Math.sin(t))*Math.pow(Math.abs(Math.sin(t)),power)],240)}}
if(s.type==='polygonspiral'){let sides=3+Math.round(tw*5);for(let j=0;j<n;j++){let r=185*Math.pow(.94,j),a=j*.11;path(Array.from({length:sides+1},(_,i)=>[r*Math.cos(i/sides*TAU+a),r*Math.sin(i/sides*TAU+a)]))}}
if(s.type==='cardioid'){let count=n*3,m=2+Math.round(tw*4);circle(0,0,180);for(let i=0;i<count;i++){let a=i/count*TAU,b=a*m;line([180*Math.cos(a),180*Math.sin(a)],[180*Math.cos(b),180*Math.sin(b)])}}
if(s.type==='sunflower'){let count=n*12,angle=Math.PI*(3-Math.sqrt(5))+tw*.04;for(let i=0;i<count;i++){let r=180*Math.sqrt(i/count),a=i*angle;dot(r*Math.cos(a),r*Math.sin(a),1.1+55/Math.sqrt(count))}}
if(s.type==='dotspiral'){let count=n*10,turns=2+tw*6;for(let i=0;i<count;i++){let u=i/(count-1),a=u*TAU*turns,r=12+u*168;dot(r*Math.cos(a),r*Math.sin(a),1.5+u*2)}}
if(s.type==='dottorus'){for(let j=0;j<n;j++)for(let i=0;i<n;i++){let a=j/n*TAU,b=i/n*TAU+tw*a,r=125+45*Math.cos(b),p=project(r*Math.cos(a),r*Math.sin(a),45*Math.sin(b));dot(...p,1.6+s.stroke*.25)}}
if(s.type==='dotripple'){for(let j=0;j<n;j++)for(let i=0;i<n;i++){let x=(i/(n-1)-.5)*340,y=(j/(n-1)-.5)*340,r=1.2+(1+Math.cos(Math.hypot(x,y)/25-tw*TAU))*1.4;dot(x,y,r)}}
if(s.type==='dotdiamond'){for(let j=0;j<n;j++)for(let i=0;i<n;i++){let x=(i/(n-1)-.5)*340,y=(j/(n-1)-.5)*340,d=(Math.abs(x)+Math.abs(y))/190;if(d<=1)dot(x,y,1+(1-d)*(2+tw*3))}}


if(['catenoid','paraboloid','onion','droplet'].includes(s.type)){const radius=u=>s.type==='catenoid'?40*Math.cosh((u-.5)*(3+tw)):s.type==='paraboloid'?165*Math.sqrt(u):s.type==='droplet'?170*Math.sin(Math.PI*u)*(.35+.65*u):150*Math.pow(Math.sin(Math.PI*u),.35+tw);for(let j=0;j<n;j++){let u=j/(n-1),r=radius(u);curve(t=>project(r*Math.cos(t),r*Math.sin(t),(u-.5)*290))}for(let j=0;j<Math.max(6,Math.round(n/2));j++){let a=j/Math.max(6,Math.round(n/2))*TAU;path(Array.from({length:101},(_,i)=>{let u=i/100,r=radius(u);return project(r*Math.cos(a+tw*u),r*Math.sin(a+tw*u),(u-.5)*290)}))}}
if(s.type==='dome'){let rows=Math.max(3,Math.round(n/3)),cols=n;for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const pt=(a,b)=>{let u=a/rows*Math.PI/2,v=b/cols*TAU+tw*a/rows;return project(180*Math.sin(u)*Math.cos(v),180*Math.sin(u)*Math.sin(v),180*Math.cos(u)-75)};path([pt(j,i),pt(j+1,i),pt(j+1,i+1),pt(j,i)]);line(pt(j,i),pt(j,i+1))}}
if(s.type==='twistedprism'){let sides=3+Math.round(tw*5);const pt=(j,i)=>{let u=j/(n-1),a=i/sides*TAU+u*tw*2;return project(115*Math.cos(a),115*Math.sin(a),(u-.5)*270)};for(let j=0;j<n;j++)path(Array.from({length:sides+1},(_,i)=>pt(j,i)));for(let i=0;i<sides;i++)path(Array.from({length:n},(_,j)=>pt(j,i)))}
if(s.type==='doublespiral'){for(let j=0;j<Math.max(1,Math.round(n/6));j++)for(let side of [-1,1])path(Array.from({length:900},(_,i)=>{let u=i/899,a=u*TAU*(2+tw*5)+j*.05;return [side*u*180*Math.cos(a),side*u*180*Math.sin(a)]}))}
if(s.type==='astroid'){for(let j=0;j<n;j++){let r=180*(j+1)/n,p=2+tw*3;curve(t=>[r*Math.sign(Math.cos(t))*Math.pow(Math.abs(Math.cos(t)),p),r*Math.sign(Math.sin(t))*Math.pow(Math.abs(Math.sin(t)),p)])}}
if(s.type==='nephroid'){for(let j=0;j<n;j++){let r=43*(j+1)/n;curve(t=>[r*(3*Math.cos(t)-Math.cos(3*t+tw)),r*(3*Math.sin(t)-Math.sin(3*t+tw))])}}
if(s.type==='lemniscate'){for(let j=0;j<n;j++){let a=185*(j+1)/n;curve(t=>[a*Math.cos(t)/(1+Math.sin(t)**2),a*Math.cos(t)*Math.sin(t)/(1+Math.sin(t)**2)*( .5+tw)])}}
if(s.type==='chrysanthemum'){for(let j=0;j<Math.max(2,Math.round(n/4));j++)curve(t=>{let r=(135-j*8)*(1+.22*Math.cos((8+Math.round(tw*8))*t))*(.85+.15*Math.sin(3*t));return [r*Math.cos(t),r*Math.sin(t)]},500)}
if(s.type==='starweave'){let points=5+Math.round(tw*7);for(let j=0;j<n;j++){let r=185*(j+1)/n,a=j*.025;path(Array.from({length:points*2+1},(_,i)=>{let t=i/(points*2)*TAU+a,k=i%2?.4:1;return [r*k*Math.cos(t),r*k*Math.sin(t)]}))}}
if(s.type==='hexnest'||s.type==='trianglefan'){let sides=s.type==='hexnest'?6:3;for(let j=0;j<n;j++){let u=j/(n-1),r=185*(1-u*.9),a=tw*u*2;path(Array.from({length:sides+1},(_,i)=>[r*Math.cos(i/sides*TAU+a),r*Math.sin(i/sides*TAU+a)]))}}
if(s.type==='wavecircle'){for(let j=0;j<n;j++){let y=(j/(n-1)-.5)*350,w=Math.sqrt(180*180-y*y);path(Array.from({length:121},(_,i)=>{let x=(i/120-.5)*2*w;return [x,y+15*Math.sin(x/30+tw*TAU)*Math.sin(i/120*Math.PI)]}))}}
if(s.type==='offsetellipses'){for(let j=0;j<n;j++){let u=j/(n-1),a=u*Math.PI*tw;curve(t=>{let x=125*Math.cos(t),y=60*Math.sin(t);return [x*Math.cos(a)-y*Math.sin(a)+(u-.5)*100,x*Math.sin(a)+y*Math.cos(a)]})}}
if(s.type==='rippledisc'){for(let j=1;j<=n;j++){let r=j/n*165;curve(t=>project(r*Math.cos(t),r*Math.sin(t),25*Math.sin(r/20+tw*TAU)))}for(let j=0;j<12;j++){let a=j/12*TAU;path(Array.from({length:101},(_,i)=>{let r=i/100*165;return project(r*Math.cos(a),r*Math.sin(a),25*Math.sin(r/20+tw*TAU))}))}}
if(s.type==='braid'){const strands=3+Math.round((n-6)/54*9);for(let j=0;j<strands;j++){let offset=(j/(strands-1)-.5)*48;for(let k=0;k<3;k++)path(Array.from({length:181},(_,i)=>{let u=i/180;return [(u-.5)*350,65*Math.sin(u*TAU*(1+tw*2)+k*TAU/3)+offset]}))}}
if(s.type==='conchoid'){for(let j=0;j<n;j++){let r=100+j/(n-1)*45;curve(t=>{let d=r*(.6+tw*.4)+70*Math.cos(t);return [d*Math.cos(t)-35,d*Math.sin(t)]})}}
if(s.type==='cycloid'){for(let j=0;j<n;j++)path(Array.from({length:301},(_,i)=>{let t=i/300*TAU*2;return [(t-TAU)*28-25*Math.sin(t),40*Math.cos(t)*( .5+tw)+(j/(n-1)-.5)*150]}))}
if(['dotcone','dotcylinder','dotvase'].includes(s.type)){for(let j=0;j<n;j++){let u=j/(n-1),r=s.type==='dotcone'?u*150:s.type==='dotcylinder'?125:80+45*Math.cos(u*TAU+tw*2);for(let i=0;i<n;i++){let a=i/n*TAU+tw*u,p=project(r*Math.cos(a),r*Math.sin(a),(u-.5)*280);dot(...p,1.8)}}}
if(s.type==='dotflower'){let petals=3+Math.round(tw*8);for(let j=1;j<=n;j++)for(let i=0;i<n;i++){let a=i/n*TAU,r=(105+65*Math.cos(petals*a))*j/n;dot(r*Math.cos(a),r*Math.sin(a),1.5)}}

}
